# Site settings
title: Wayne Tay's Site
description: "A personal site using the Forty Jekyll theme"
url: "https://waynetay.github.io"
baseurl: "" # root deployment
author:
  name: "Wayne Tay"
  email: "your.email@example.com"

# Build settings
markdown: kramdown
theme: minima # Required by GitHub Pages even though Forty is custom
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific options
menu:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Wayne Tay"

# Social links
social:
  twitter: "waynetay"
  github: "waynetay"
  linkedin: "waynetay"

# GitHub Pages settings
github:
  repository: "waynetay/waynetay.github.io"

